version: '3.8'
services:
  mongodb:
    image: 'mongo'
    container_name: mongodb
    volumes:
      - data:/data/db
    #environment:
    #  MONGO_INITDB_ROOT_USERNAME: user
    #  MONGO_INITDB_ROOT_PASSWORD: pass
    env_file:
      - ./env/mongo.env
  nodeapp:
    build:
      dockerfile: Dockerfile
    container_name: nodeapp
    ports:
      - '3000:3000'
    env_file:
      - ./env/node.env
    depends_on:
      - mongodb
volumes:
  data: