version: '3.8'
services:
  mongo:
    image: 'mongo'
    volumes:
      - data:/data/db
    environment:
      MONGO_INITDB_ROOT_USERNAME: testUser
      MONGO_INITDB_ROOT_PASSWORD: testPassword
  node:
    image: node:14
    working_dir: /bin/www
    entrypoint: ['npm']
    ports:
      - '3000:3000'
    depends_on:
      - mongo
    volumes:
      - ./src:/var/www/html
volumes:
  data: